apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: app-demo-cluster
  namespace: app-demo
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: guaranteed-medium
      storageClass: dc1-cls1-ds1
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 16Gi
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
    - name: app-demo-cluster-node-pool-1
      replicas: 1
      vmClass: guaranteed-large
      storageClass: dc1-cls1-ds1
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 64Gi
      tkr:
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
  settings:
    storage:
      defaultClass: dc1-cls1-ds1
    network:
      cni:
        name: antrea
