apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  virtualhost:
    fqdn: sock-shop.poclab.me
  routes:
    - conditions:
      - prefix: /
      services:
        - name: front-end
          port: 80
